version: "3.9"

services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: chords_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
    ports:
      - "5433:5432"          # host port 5433 -> container 5432
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build: ./backend
    env_file: .env.example
    depends_on:
      - db
    ports:
      - "8000:80"           # host 8000 -> container 80

  frontend:
    build:
      context: ./frontend
      args:
        VITE_API_URL: http://localhost:8000   # passed to Vite at build time
    depends_on:
      - backend
    ports:
      - "3000:80"           # host 3000 -> container 80

volumes:
  pgdata:
