services:
  backend:
    build: ./backend
    env_file: .env
    ports:
      - "8080:80"          # наружу 8080 → внутри 80
    depends_on: [db]

  frontend:
    build:
      context: ./frontend
      args:
        VITE_API_URL: http://localhost:8080
    ports:
      - "3000:80"
    depends_on: [backend]
