// frontend/src/pages/Chords/ChordDetailsPage.tsx
import React, { useEffect, useState } from "react";
import { useParams } from "react-router-dom";
import axios from "axios";

import { ChordDTO } from "../../api/chords";

const ChordDetailsPage: React.FC = () => {
  const { id } = useParams<{ id: string }>();

  const [chord,   setChord] = useState<ChordDTO | null>(null);
  const [error,   setError] = useState<string | null>(null);
  const [loading, setLoad ] = useState(true);

  useEffect(() => {
    if (!id) return;

    (async () => {
      try {
        const { data } = await axios.get<ChordDTO>(`/api/chords/${id}`);
        setChord(data);
      } catch (e) {
        setError("Не удалось загрузить аккорд");
        console.error(e);
      } finally {
        setLoad(false);
      }
    })();
  }, [id]);

  if (loading) return <p>Загрузка…</p>;
  if (error)   return <p className="text-red-600">{error}</p>;
  if (!chord)  return null;

  return (
    <section className="p-4">
      <h1 className="text-2xl font-bold mb-4">{chord.name}</h1>
      <pre className="bg-gray-100 p-2 rounded">
        {JSON.stringify(chord, null, 2)}
      </pre>
    </section>
  );
};

export default ChordDetailsPage;
