name: e2e-playwright

on:
  pull_request:
  workflow_dispatch:

jobs:
  e2e:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15-alpine
        env:
          POSTGRES_DB: chords_db
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: secret
        ports: [5432:5432]
        options: >-
          --health-cmd="pg_isready -U postgres"
          --health-interval=5s
          --health-timeout=5s
          --health-retries=5

    steps:
      - uses: actions/checkout@v4

      - name: Backend up (Docker compose)
        run: docker compose -f docker-compose.yml up -d backend

      - uses: actions/setup-node@v3
        with:
          node-version: "20"

      - run: npm install --legacy-peer-deps
        working-directory: tests/e2e      # припустимо, e2e‑тести тут
      - run: npx playwright install --with-deps
      - run: npx playwright test

