name: preview-env

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  render-preview:
    runs-on: ubuntu-latest
    env:
      RENDER_SERVICE_ID: ${{ secrets.RENDER_SERVICE_ID }}   # <- створи в Render
      RENDER_API_KEY:  ${{ secrets.RENDER_API_KEY }}

    steps:
      - uses: actions/checkout@v4
      - name: Trigger Render deploy (preview)
        run: |
          curl -X POST \
            -H "Authorization: Bearer $RENDER_API_KEY" \
            -H "Content-Type: application/json" \
            -d '{ "clearCache": true }' \
            https://api.render.com/v1/services/$RENDER_SERVICE_ID/deploys

